## **Homework 2**

### Create a copy of the notebook to start answering the questions. Name your notebook in the format HW1_lastname_firstname.ipynb to facilitate the grading process. 

### Answer all the questions, test your code to ensure there are no errors and the results are as expected. Once you have answered all the questions, save the final copy, then go to File-> click on Download.ipynb. Once the local copy has been downloaded, submit your file on Blackboard under the corresponding assignment section. Also provide us a link to your notebook during submission. 

### **The due date of this homework is 02/12/2021 (Friday).**

### Please ensure you follow all the steps mentioned in the homework.

### All the questions have a sample input and output to help you understand the question.

### You can submit your solutions any number of times until the deadline.


**Q1. Lets consider your data is like the below cell:**

**Q1-1**: Write a program that create a dataframe from the data.

**Q1-2:** Select people that are psychologist or teacher and their number of cars is greater than their family size.

**Q1-3:** Select people who have at most 2 family members and at least 1 car.

**Q1-4:** Write a code that get number of unique jobs in this dataset.





In [ ]:
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}

In [ ]:
import pandas as pd
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}
# Type your solution here
#creating data frame for question 1-1
frame = pd.DataFrame(data)

#selecting the conditions given in Q1-2
frame[(frame.job == "Psychologist", "Teacher") and (frame.family_size < frame.num_cars)] 

#selecting the conditions given in Q1-3
frame[(frame.family_size <= 2) & (frame.num_cars > 0)]

#finding number of uniqye jobs for Q1-4
uniqueJobs = len(pd.unique(frame["job"]))
print("unique jobs: ", uniqueJobs)





unique jobs:  4


**Q2. Lets consider you have two series like the below cell. Compute the mean of weights of each fruit.**

In [ ]:
import numpy as np
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

In [ ]:
# Type your solution here
#converting the series into a numpy array
np_array = np.array(list(zip(fruit, weights)))

#converting the array into a data frame and converting the weights into string
fruit_frame = pd.DataFrame(np_array, columns=["Fruit","Weight"])
fruit_frame[["Weight"]] = fruit_frame[["Weight"]].apply(pd.to_numeric)

#grouping by fruit, then finding the mean
fruitGroup = fruit_frame.groupby("Fruit")
meanFruit = fruitGroup.mean()
print(meanFruit)


          Weight
Fruit           
apple   7.000000
banana  5.000000
carrot  5.166667


**Q3. Consider the below course_name array:**

**Q3-1**: Write a NumPy program to get the indices of the sorted elements of **course_name** array.

**Q3-2:** Write numpy code to check whether each element of **course_name** array starts with "P".


In [ ]:
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])

In [ ]:
# Type your solution here
#solution for #Q3-1
np.argsort(course_name)


#solution for #Q3-2

#creating a new aray to store the strings that start with P
p_array = ([])
#for loop to check whether the first element of each string starts with P
for i in range(len(course_name)):
  if course_name[i][0] == "P":
    p_array.append(course_name[i])
  else:
    pass
print(p_array)

  



['Python', 'PHP']
S


**Q4. Consider the below student_id array:**

**Q4-1:** Reverse the **student_id** array. Print both original and reversed array.

**Q4-2:** Get the 3-largest values of **student_id** array.

In [ ]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

In [46]:
# Type your solution here

#Q4-1
#reversing the array and printing both original and new arrays for 
reverse_id = np.flip(student_id)
print("Orginal:", student_id)
print("Reversed:", reverse_id)

#Q4-2
sorted_id = np.sort(student_id)
reverse_sort = np.flip(sorted_id)

print("The three largest values are:", reverse_sort[0:3])






Orginal: [1023 5202 6230 1671 1682 5241 4532]
Reversed: [4532 5241 1682 1671 6230 5202 1023]
The three largest values are: [6230 5241 5202]


# **Q5: Write a numpy program to print sum of all the multiples of 3 or 5 below 100**

In [59]:
# Type your solution here
#creating an array of integers between 1 and 100
numArr = np.arange(1,100)
#creating an empty array to store all the multiplies of 3 and 5
sumArr = ([])
#for loop that iterates over the first array and appends multiples of 3 and 5 to the new array
for i in numArr:
  if i % 3 == 0 or i % 5 == 0:
    sumArr.append(i)
print(sumArr)
print("The sum is:", np.sum(sumArr))

# Hint: you can use arange to start off

[3, 5, 6, 9, 10, 12, 15, 18, 20, 21, 24, 25, 27, 30, 33, 35, 36, 39, 40, 42, 45, 48, 50, 51, 54, 55, 57, 60, 63, 65, 66, 69, 70, 72, 75, 78, 80, 81, 84, 85, 87, 90, 93, 95, 96, 99]
The sum is: 2318


**Q6. Consider the below array.**

Q6.1. Write a code to swap column 1 with column 2.

Q6.2. Write a code to swap row 0 with row 1.

In [16]:
import numpy as np

arr = np.arange(12).reshape(3,4)
print("Original Array:")
print(arr)



Original Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [15]:
# Type your solution here
#Q6-1
#swapping array
arr[:,[1,2]]=arr[:,[2,1]]
print("Swapping columns 1 and 2:")
print(arr)

#Q6-2
arr[:,[0,1]]=arr[:,[1,0]]
print("Swapping columns 0 and 1:")
print(arr)

Swapping columns 1 and 2:
[[ 2  1  0  3]
 [ 6  5  4  7]
 [10  9  8 11]]
Swapping columns 0 and 1:
[[ 1  2  0  3]
 [ 5  6  4  7]
 [ 9 10  8 11]]
